config/routes.rb
PortrayApp::Application.routes.draw do

get "/about_us", :controller => "main", :action => :about_us, :as => :about

get "/our_partner", :controller => "main", :action => :our_partner, :as => :partner

get "/advertising_solutions", :controller => "main", :action => :advertising_solutions, :as => :ads

get "/cafeteria_solutions", :controller => "main", :action => :cafeteria_solutions, :as => :cafs

get "/", :controller => "main", :action => :home, :as => :root

get "/contact" => "main#contact", :action => :home, :as => :contact

get "/thanks", :controller => "main", :action => :thanks, :as => :site_thanks

match "/thanks" => "main#thanks", as: "site_thanks", via: :POST

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def about_us
  end
  
  
  def our_partner
  end
  
  
  def advertising_solutions
  end
  
  
  def cafeteria_solutions
  end
  
  def landing
    render layout: "splash"
  end
  
  def home
    render layout: "home"
  end
  
  def thanks

      name = params[:name]
      email = params[:email]
      message = params[:message]

      unless name.blank? && email.blank? && message.blank?
        ContactMailer.contact_form_email(name, email, message).deliver
      else
        redirect_to session[:return_to], notice: "Please fill in all the fields!"
      end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portray Advertising - The World's Smartest Food Trays</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Assets -->
	<%= stylesheet_link_tag 'main.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'bootstrap.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'responsive.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'style.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'camera.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'portfolio.css', :media => 'screen, projection' %>
	<%= stylesheet_link_tag 'elements.css', :media => 'screen, projection' %>
	<%= javascript_include_tag "application" %>
	
	<link href="/assets/jquery.bxslider.css" rel="stylesheet" />
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,900,400italic' rel='stylesheet' type='text/css'>			
		<!-- end Assets -->
	
	<%= favicon_link_tag 'portray_p.ico' %>

	<!-- Meta -->

	<meta name="description" content="Portray advertising provides an innovative marketing platform for businesses in food courts and cafeterias. Portray advertising sells advertisements in the interior of modern designed food trays.">

	<!-- end Meta -->

	<!-- Javascripts -->

		<script type="text/javascript">var switchTo5x=true;</script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
		<script src="/assets/jquery.bxslider.min.js"></script>
		<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
		<script type="text/javascript">stLight.options({publisher: "e03a96b6-9381-4bf1-b222-4bf9e2977573", doNotHash: true, doNotCopy: true, hashAddressBar: false});</script>
		
		<script type="text/javascript">
			$(document).ready(function(){

			  $('ul.bxslider').bxSlider({
		 		 pagerCustom: '#pager',
		 		 adaptiveHeight: true,
		 		 controls: true,
		 		 auto: true,
		 		 pause: 4000
		    	});

				$(function() {
				   $("#pager a").click(function() {
				      // remove classes from all
				      $("#pager a").removeClass("active");
				      // add class to the one we clicked
				      $(this).addClass("active");
				   });
				});
				
				 $('.dropdown_toggle').click(function(e) {
				  	if ($(this).parent().is('.clicked')) {
				  		$('.dropdown_toggle').removeClass('clicked');
				  		$('.dropdown_menu').fadeOut('fast');
				  	}
				  	else
				  	{
				  		$(this).parent().find('.dropdown_menu').fadeIn('fast', function() {
				  			$(this).addClass('opened');
				  		});

				  		// This stops the click event from bubbling up the DOM tree
				  		e.stopPropagation();
				  	}
				  });

				  $('body').click(function() {
				  	$('.dropdown_menu').fadeOut('fast', function() {
				  		$(this).removeClass('opened');
				  	});
				  });

			});

		</script>
		
	<!-- End JS -->

</head>
<body>

	<div id="container">
		<header>
		<%= render "shared/header" %>
		</header>

		<%= yield %>
	
	</div>
		<%= render "shared/footer" %>

		<script> 
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ 
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), 
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) 
		})(window,document,'script','//http://www.google-analytics.com/analytics.js','ga'); 

		ga('create', 'UA-43548331-1', 'portrayadvertising.com'); 
		ga('send', 'pageview'); 

		</script>
		
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portray Advertising - The World's Smartest Food Trays</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Assets -->
<%= stylesheet_link_tag 'main.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'bootstrap.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'responsive.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'style.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'camera.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'portfolio.css', :media => 'screen, projection' %>
<%= stylesheet_link_tag 'elements.css', :media => 'screen, projection' %>
<%= javascript_include_tag "application" %>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,900,400italic' rel='stylesheet' type='text/css'>			
	<!-- end Assets -->
	
	<%= favicon_link_tag 'portray_p.ico' %>

	<!-- Meta -->

	<meta name="description" content="Portray advertising provides an innovative marketing platform for businesses in food courts and cafeterias. Portray advertising sells advertisements in the interior of modern designed food trays.">

	<!-- end Meta -->

</head>
<body>

		<header>
		<%= render "shared/header" %>
		</header>

		<%= yield %>
	
		<%= render "shared/footer" %>
		
		<script type="text/javascript" src="/assets/jquery.js"></script>
		<script type="text/javascript" src="/assets/bootstrap.js"></script>
		<script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
		<script type="text/javascript" src="/assets/camera.js"></script>
		<script type="text/javascript" src="/assets/jquery.ui.totop.js"></script>
		<script type="text/javascript" src="/assets/prettify.js"></script>
		<script type="text/javascript" src="/assets/application.js"></script>
		<script type="text/javascript" src="/assets/jquery.cookie.js"></script>
		<script type="text/javascript" src="/assets/jquery.quicksand.js"></script>
		<script type="text/javascript" src="/assets/jquery.mobile.customized.min.js"></script>
		<script type="text/javascript" src="/assets/accordion.js"></script>
		<script type="text/javascript" src="/assets/tabs.js"></script>
		<script type="text/javascript" src="/assets/nav-small.js"></script>
				<script type="text/javascript" src="/assets/superfish.js"></script>
				
				<script> 
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ 
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), 
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) 
				})(window,document,'script','//http://www.google-analytics.com/analytics.js','ga'); 

				ga('create', 'UA-43548331-1', 'portrayadvertising.com'); 
				ga('send', 'pageview'); 

				</script>
				
		<script>
		      $(document).ready(function(){   
		         jQuery('.camera_wrap').camera();
							
						$(function() {
							$(".video ")
							.find("span")
							.hide()
							.end()
							.hover(function() {
								$(this).find("span").stop(true, true).fadeIn();

							}, function() {
								$(this).find("span").stop(true, true).fadeOut();
							});
						});
						
						var ifra;
						$(".video").click(function(){
						if ( ifra ) {
						ifra.appendTo("body");
						ifra = null;
						}  
						$("#overlay_form").fadeIn(500);
						 $("#popi-bg").css({
						"opacity": "0.7"
						}); 
						$("#popi-bg").fadeIn("fast");
						positionPopup();
						});


						$("#close2, #popi-bg").click(function(){

						$("#overlay_form").fadeOut(300);

						$("#popi-bg").fadeOut("fast");
						if ( ifra ) {
						ifra.appendTo("body");
						ifra = null;
						} else {
						ifra = $("#overlay_form").detach();
						}

						});

						function positionPopup(){
						if(!$("#overlay_form").is(':visible')){
						return;
						}
						$("#overlay_form").css({
						left: ($(window).width() - $('#overlay_form').width()) / 2.2,
						top: ($(window).width() - $('#overlay_form').width()) / 3.2,
						position:'absolute'
						});
						}
						$(window).bind('resize',positionPopup);
						
						 $('.dropdown_toggle').click(function(e) {
						  	if ($(this).parent().is('.clicked')) {
						  		$('.dropdown_toggle').removeClass('clicked');
						  		$('.dropdown_menu').fadeOut('fast');
						  	}
						  	else
						  	{
						  		$(this).parent().find('.dropdown_menu').fadeIn('fast', function() {
						  			$(this).addClass('opened');
						  		});

						  		// This stops the click event from bubbling up the DOM tree
						  		e.stopPropagation();
						  	}
						  });

						  $('body').click(function() {
						  	$('.dropdown_menu').fadeOut('fast', function() {
						  		$(this).removeClass('opened');
						  	});
						  });
						
		        });
					
		</script>
			
</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portray Advertising - The World's Smartest Food Trays</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Assets -->
		
	<!-- end Assets -->
	
	<%= favicon_link_tag 'portray_p.ico' %>
	
	<style type="text/css">
		h1 { font-family:Helvetica, Arial, sans-serif; font-weight:100; }
		.main { width:50%;margin:0 auto; }
		.main img { width:100%; margin:100px 0 20px 0;text-transform:uppercase;}
	</style>
	
</head>

<body style="text-align:center;background-color:#ddd;">
	<div class="main">
<%= yield %>
	</div>
	
</body>
</html>

app/views/main/_contact_form.html.erb
<div id="contact_form" class="open_message">
<div class="modal hide" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" onclick="$.colorbox.close(); return false;" data-dismiss="modal">×</button>
    <h3>Contact Us</h3>
  </div>
  <div class="modal-body">
    <%= form_tag(site_thanks_path, :method => :post) do %>

		<div id="new_message_action">

	      <% if current_user %>
	        <%= hidden_field_tag "name", current_user.full_name %>
	        <%= hidden_field_tag "email", current_user.email %>
	        <p>Your message will be sent to us with the reply address:</p>
						<p><strong><%= current_user.email%></strong></p>
						<p>For all account questions please file a <%= link_to "Support Ticket", account_tickets_path(current_user) %>.</p>
	      <% else %>
	        <%= label :name_label, "Your name:" %>
					<%= text_field_tag :name, '', size: 64, class: "name" %>

	        <%= label :email_label, "Your email:" %>
					<%= text_field_tag :email, '', size: 64, class: "email" %>
	      <% end %>

				<%= label :messsage_label, "Message:" %>
	      <%= text_area_tag :message %>

			</div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" onclick="$.colorbox.close(); return false;" data-dismiss="modal">Close</a>
    <%= submit_tag "Send", id:"message_submit", class: "btn btn-primary"%>
  </div>
<% end %>
</div>

</div>

app/views/main/about_us.html.erb
<div id="opener_about_us">
</div>

<div id="middle_content">
	
	<h2 class="title">About Portray Advertising
		<span class='st_email_large icon_right'></span>
		<span class='st_twitter_large icon_right'></span>
		<span class='st_facebook_large icon_right'></span>
	</h2>
	
	<p class="text">As the world continues to advance, advertiser’s jobs have become increasingly more difficult.   Viewers are now capable of skipping over 		commercials, newspapers are no longer the go-to source for information and ad-free radio subscriptions are on the rise.  This is not to say that traditional advertising cannot be successful, but a progressive approach must be taken. With 90% of Canadians visiting the mall at least once a month and 62% of all mall visitors eating at a food court, Portray Advertising has created a sophisticated food tray that allows businesses to insert advertisements and engage with daily shoppers.</p>
<div style="clear:both;width:100%;margin:10px 0;text-align:center;">
	<%= image_tag "/assets/portray_pics/tray_overlaps_375.png", alt: "Portray Product", class: "framed" %>
	<%= image_tag "/assets/portray_pics/black_tray2_375.png", alt: "Portray Product", class: "framed framed-second" %>
</div>
<br/>
	<p id="quote">Our innovative design is water-clear transparent to ensure high visibility and has enhanced ergonomics to improve balance and ease of holding.</p>
<br/>
<br/>
</div>

app/views/main/cafeteria_solutions.html.erb
<div id="opener_caf_solutions">
</div>

<div id="middle_content">
	
	<h2 class="title">Cafeteria Solutions
		<span class='st_email_large icon_right'></span>
		<span class='st_twitter_large icon_right'></span>
		<span class='st_facebook_large icon_right'></span>
	</h2>

<p class="text">Portray Advertising understands the importance of increasing the bottom line, so we built our
	business around it. We provide food courts with high quality food trays at no cost and a revenue sharing
	program for zero investment and no management. Our patented food tray incorporates contemporary
	ergonomics and a modern design that will “wow” your customers!</p>

  <div class="row-fluid">
    <div class="span12">
      <ul class="thumbnails">
        <li class="span6">
          <div class="thumbnail"> <svg version="1.0" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
						 width="100px" height="99.999px" viewBox="0 0 100 99.999" enable-background="new 0 0 100 99.999" xml:space="preserve">
					<path d="M49.973,99.999H49.97c-13.356-0.007-25.908-5.212-35.347-14.657C5.181,75.89-0.012,63.328,0,49.966
						c-0.012-13.335,5.177-25.884,14.614-35.327C24.049,5.201,36.594,0,49.94,0h0.062c13.351,0,25.907,5.201,35.348,14.638
						C94.789,24.077,99.991,36.623,100,49.97c-0.009,13.37-5.216,25.927-14.661,35.373C75.893,94.787,63.335,99.992,49.973,99.999
						L49.973,99.999z M49.94,11.494c-10.273,0-19.931,4.003-27.196,11.273c-7.262,7.27-11.258,16.928-11.25,27.2
						c-0.008,10.298,3.992,19.972,11.262,27.248c7.267,7.276,16.932,11.283,27.215,11.289c21.233-0.011,38.52-17.296,38.533-38.533
						c-0.013-21.213-17.283-38.477-38.501-38.477H49.94L49.94,11.494z"/>
					<path d="M54.323,44.643V33.436c3.194,0.23,5.688,3.401,5.983,6.637h10.607c0.012-10.883-9.883-16.604-16.7-17.025v-7.344H44.097
						v7.344c-2.977,0.023-16.39,3.817-16.375,15.989c-0.016,10.835,9.657,13.791,16.375,14.742v12.24
						c-4.894-1.386-5.789-5.154-6.473-8.268H26.853c0.69,12.18,11.393,17.849,17.244,18.713v7.505h10.227v-7.396
						c8.087-0.436,17.666-7.419,17.679-16.972C71.989,48.612,62.447,45.497,54.323,44.643z M44.151,42.845
						c-7.202-0.112-7.345-8.004,0-9.302V42.845z M54.433,66.074V55.521C63.354,55.765,64.346,64.66,54.433,66.074z"/>
					</svg>
            <h2 class="tri-feature">Free Money</h2>
            <p class="p0">Portray Advertising provides food courts with percentage of advertising sales, creating a new revenue stream for no investment or management.</p>
          </div>
        </li>
				<li class="span6">
					<div class="thumbnail"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
					<polygon points="11,89 11,0 0,0 0,100 100,100 100,89 "/>
					<polygon points="71.031,23.609 78.689,29.491 62.712,48.739 44.785,34.514 19.14,64.428 25.562,69.934 45.898,46.202 63.921,60.509   85.384,34.708 93,40.631 93,18.066 "/>
					</svg>
					    <h2 class="tri-feature">Eliminate Costs</h2>
	            <p class="p0">Portray Advertising provides cafeterias with modern designed food trays for free, eliminating all existing and future tray operating costs.</p>
	          </div>
	        </li>
				</ul>
			</div>
		</div>
		
		<div class="row-fluid">
	    <div class="span12">
	      <ul class="thumbnails">
	        <li class="span6">
	          <div class="thumbnail"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" width="100px" height="77.519379845px" viewBox="0 0 129.469 100" enable-background="new 0 0 129.469 100" xml:space="preserve">
						<path d="M92.494,57.127c-1.539,0-2.786,1.246-2.786,2.785c0,0.428,0.104,0.828,0.278,1.192l-0.027,0.012  c1.729,3.679,2.708,7.775,2.708,12.102s-0.979,8.424-2.708,12.103l0.027,0.013c-0.174,0.363-0.278,0.765-0.278,1.193  c0,1.538,1.247,2.784,2.786,2.784c1.212,0,2.233-0.779,2.615-1.86c1.998-4.336,3.128-9.151,3.128-14.231s-1.13-9.896-3.128-14.231  C94.728,57.904,93.706,57.127,92.494,57.127z"/>
						<path d="M106.763,51.834c-1.538,0-2.784,1.248-2.784,2.785c0,0.425,0.102,0.821,0.271,1.183l-0.014,0.006  c2.538,5.282,3.986,11.183,4.041,17.412c-0.055,6.229-1.503,12.13-4.041,17.413l0.014,0.006c-0.17,0.359-0.271,0.758-0.271,1.181  c0,1.538,1.246,2.785,2.784,2.785c1.175,0,2.175-0.728,2.584-1.758c2.833-5.963,4.446-12.61,4.501-19.626  c-0.055-7.016-1.668-13.663-4.501-19.625C108.938,52.563,107.938,51.834,106.763,51.834z"/>
						<path d="M123.938,48.227c-0.03-0.081-0.067-0.157-0.104-0.233l0,0c-0.456-0.918-1.393-1.556-2.487-1.556  c-1.539,0-2.785,1.247-2.785,2.785c0,0.405,0.091,0.787,0.246,1.135l-0.013,0.006c3.268,6.942,5.103,14.687,5.103,22.855  c0,8.169-1.835,15.913-5.103,22.855l0.013,0.006c-0.155,0.348-0.246,0.729-0.246,1.135c0,1.539,1.246,2.785,2.785,2.785  c1.095,0,2.031-0.638,2.487-1.555c0-0.001,0-0.001,0-0.001c0.037-0.077,0.074-0.153,0.104-0.233  c3.543-7.602,5.53-16.067,5.53-24.991C129.469,64.295,127.48,55.829,123.938,48.227z"/>
						<path d="M83.819,58.562l-7.929-19.961c0,0-0.817-8.27-1.564-11.437C71.025,12.923,55.149,0,37.931,0C16.986,0,0,16.989,0,37.952  c0,12.106,5.67,22.896,14.5,29.842v32.204h40.486V88.384h5.945c8.26,0,14.959-6.7,14.959-14.968V62.811h5.087  c1.689,0,3.069-1.375,3.069-3.059C84.048,59.328,83.971,58.922,83.819,58.562z M62.691,47.103c-2.865,0-5.188-2.322-5.188-5.188  c0-2.865,2.323-5.188,5.188-5.188c2.866,0,5.188,2.323,5.188,5.188C67.88,44.781,65.558,47.103,62.691,47.103z"/>
						</svg>
	            <h2 class="tri-feature">Brand Interaction</h2>
	            <p class="p0">Portray Advertising provides a relevant marketing platform for retail tenants to communicate with shoppers while they are within close proximity and in a purchasing state of mind.</p>
	          </div>
	        </li>
					<li class="span6">
						<div class="thumbnail"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
						<g id="Captions">
						</g>
						<g id="Your_Icon">
							<path fill="#000000" d="M28,55.747V92.38c0,0,0.265-2.868,15.566,2.575c0,0,10.49,4.045,18.435,4.045c0,0,10.151,0.001,15.447,0   c5.296,0,6.914-4.45,8.975-7.98c0,0,1.765-5.059,0-7.412c0,0,5.001-2.013,5.296-6.316c0,0,0.883-2.257-1.177-6.083   c0,0,2.648-3.423,3.236-9.071c0,0,0.883-1.711-1.766-3.977c0,0,3.225-6.678,1.906-10.209c0,0-1.906-6.768-5.731-6.474   c0,0-20.597,1.176-22.067,1.471s-2.264,0.294-5.104-1.471c0,0-1.369-1.766,2.75-7.651c0,0,5.003-10.003,6.179-15.595   c0,0,1.473-9.71-6.473-15.3c0,0-3.825-2.354-6.179,0c0,0-0.588,1.178-1.177,9.417c0,0-0.589,6.473-5.002,12.062   c0,0-9.314,8.239-11.962,15.006C39.152,39.417,35,50.012,28,55.747z"/>
							<path fill="#000000" d="M3.152,53.412C0.28,78.038,8.556,95,8.556,95H25V53.437C15,52.176,3.152,53.412,3.152,53.412z    M17.282,90.286c-1.703,0-3.083-1.381-3.083-3.084c0-1.702,1.38-3.083,3.083-3.083c1.702,0,3.083,1.381,3.083,3.083   C20.365,88.905,18.984,90.286,17.282,90.286z"/>
						</g>
						</svg>
						    <h2 class="tri-feature">Quality Product</h2>
		            <p class="p0">Replace existing archaic trays with Portray Advertising’s patented modern model.</p>
		          </div>
		        </li>
					</ul>
				</div>
			</div>

<div style="clear:both;width:100%;margin:10px 0;text-align:center;">
	<%= image_tag "/assets/portray_pics/black_tray_375.png", alt: "Portray Product", class: "framed" %>
	<%= image_tag "/assets/portray_pics/eating_tray_375.png", alt: "Portray Product", class: "framed framed-second" %>
</div>
<br/>

<div class="section-4" style="width:100%;border-right:1px solid #E0E0E0;border-left:1px solid #E0E0E0;">
  <div class="container" style="width:100%;">
    <!-- Strip with button -->
    <div class="row-fluid">
      <div class="span12">
        <h2>Interested in free money and premium food trays at zero cost?</h2>
        <p>If that's not a no-brainer, we don't know what is!</p>
        <a href="#" class="btn btn-large btn-success" target="_blank"><i class="icon-arrow-right icon-white"></i>&nbsp; Let's Get Started</a> </div>
    </div>
  </div>
</div>
<br/>

</div>

app/views/main/contact.html.erb
<div id="opener_contact_us">
</div>

<div id="middle_content">
	
<h2 class="title">Contact Us</h2>

<div class="row-fluid founders">
	<div class="span6">
		<h3>Kyle Boult</h3>
		<h5>Corporate Development</h5>
		<p>204.510.6584</p>
		<p><a href="mailto:kyle@portrayadvertising.com">kyle@portrayadvertising.com</a></p>
	</div>
	<div class="span6">
		<h3>Greg Lipschitz</h3>
		<h5>Corporate Development</h5>
		<p>204.292.3879</p>
		<p><a href="mailto:greg@portrayadvertising.com">greg@portrayadvertising.com</a></p>
	</div>
</div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="section-3">
    <div class="container">
      <div class="row-fluid">
        <!-- about us -->
        <div class="span4 left-footer-block">
          <h2>About Portray</h2>
          <div class="clearfix p1">
            <p class="text-info">Portray Advertising provides a unique advertisement platform in cafeterias and food courts. We reach millions of students and consumers for roughly 23 minutes each interaction.</p>
					</div>
          <ul id="social">
            <li><a title="Twitter" href="#"><img alt="Twitter" src="/assets/social_icons/twitter.png"></a></li>
            <li><a title="Facebook" href="#"><img alt="Facebook" src="/assets/social_icons/facebook.png"></a></li>
          </ul>
					<ul id="call-to">
						<li><a href="mailto:info@portrayadvertising.com">kyle@portrayadvertising.com</a></li>
						<li>1-204-510-6584</li>
					</ul>
        </div>
        <!-- links -->
        <div class="span4">

        </div>
        <!-- logo -->
        <div class="span4 right-footer-block">
					<%= link_to image_tag("/assets/footer_logo.png"), root_path %>	
          <ul class="list" style="padding:25px 5px 0;">
				 	<% unless current_page?(about_path) %>
				 		 <li><%= link_to "About Us", about_path %></li>
				 	<% end %>
					<% unless current_page?(partner_path) %>
							<li><%= link_to "Our Partner", partner_path %></li>
					<% end %>
					<% unless current_page?(ads_path) %>
							<li><%= link_to "Advertising Solutions", ads_path %></li>
					<% end %>
					<% unless current_page?(cafs_path) %>
							<li><%= link_to "Cafeteria Solutions", cafs_path %></li>
					<% end %>
					<% unless current_page?(contact_path) || current_page?(root_path) %>
							<li><%= link_to "Contact", contact_path %></li>
					<% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- footer 2 -->
  <div class="footer-2">
    <div class="container">
      <div class="row">
        <div class="span12">© 2012-2014 Portray Advertising Inc. All rights reserved.<a href="#" id="toTop"><span id="toTopHover" style="opacity:0;"></span>
				</a></div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div id="header">
		<div id="logo_container">
			<%= link_to image_tag("/assets/portray_small_logo.png"), root_path %>
		</div>

		<nav class="navigation">
			
			<li class="norm"><%= link_to "About Us", about_path %></li>
			<li class="norm"><%= link_to "Our Partner", partner_path %></li>
			<li class="norm"><%= link_to "Advertising", ads_path %></li>
			<li class="norm"><%= link_to "Cafeteria Solutions", cafs_path %></li>
			<li class="norm"><%= link_to "Contact", contact_path, :class => "contact" %></li>
			<li class="dd-toggle">
			   <a href="javascript:;" class="dropdown_toggle">
			   <img src="/assets/menu-toggler.png" />
			   </a>
			   <ul class="dropdown_menu" style="display:none;">
			     	<li><%= link_to "About Us", about_path %></li>
						<li><%= link_to "Our Partner", partner_path %></li>
						<li><%= link_to "Advertising", ads_path %></li>
						<li><%= link_to "Cafeteria Solutions", cafs_path %></li>
						<li><%= link_to "Contact", contact_path %></li>
			   </ul>
			</li>
		</nav>
		
</div>
	
	